# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def comm_pod
    pod 'Aspects'
    pod 'Masonry'
    pod 'ReactiveObjC', '~> 3.1.0'

    pod 'IQKeyboardManager'
end

target '要掌握的' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 要掌握的

end

target 'MapKit' do
comm_pod

end


target 'BaiduMap' do
comm_pod
end


target 'RACTest' do
    comm_pod
end


target 'MVVM_RAC' do
    comm_pod
end
